#pragma once

// Environment variable names
#define ENV_APPEND    "EMERGENCY_APPEND"
#define ENV_DBG_NAME  "EMERGENCY_DEBUG_NAME"
#define ENV_DBG_OPT   "EMERGENCY_DEBUG"
#define ENV_PROGNAME  "EMERGENCY_PROGNAME"
#define ENV_DEF_DRIVE "EMERGENCY_DEFAULT_DRIVE"
#define ENV_CWD       "EMERGENCY_CWD"
#define ENV_DRIVE     "EMERGENCY_DRIVE_"
#define ENV_CODEPAGE  "EMERGENCY_CODEPAGE"
#define ENV_LOWMEM    "EMERGENCY_LOWMEM"
#define ENV_ROWS      "EMERGENCY_ROWS"
#define ENV_DOSVER    "EMERGENCY_DOSVER"
#define ENV_CPUSPEED  "EMERGENCY_CPU_SPEED"
